import sqlite3
import math

conn = sqlite3.connect('data/gaia_catalog.db')
cursor = conn.execute('SELECT x, y, z, magnitude FROM stars')
stars = cursor.fetchall()

print('=' * 70)
print('STAR DENSITY ANALYSIS')
print('=' * 70)
print()

# Calculate distances from origin
distances = [math.sqrt(x**2 + y**2 + z**2) for x, y, z, _ in stars]
distances.sort()

print(f'Total stars: {len(stars):,}')
print(f'Nearest star: {distances[0]:.1f} parsecs')
print(f'10th percentile: {distances[int(len(distances)*0.1)]:.1f} pc')
print(f'25th percentile: {distances[int(len(distances)*0.25)]:.1f} pc')
print(f'50th percentile (median): {distances[int(len(distances)*0.5)]:.1f} pc')
print(f'75th percentile: {distances[int(len(distances)*0.75)]:.1f} pc')
print(f'90th percentile: {distances[int(len(distances)*0.9)]:.1f} pc')
print(f'Farthest star: {distances[-1]:.1f} parsecs')
print()

print('Stars by distance range:')
ranges = [(0, 50), (50, 100), (100, 200), (200, 500), (500, 1000), (1000, 10000)]
for min_d, max_d in ranges:
    count = sum(1 for d in distances if min_d <= d < max_d)
    print(f'  {min_d:5d}-{max_d:5d} pc: {count:6d} stars ({count/len(stars)*100:5.1f}%)')

print()
print('=' * 70)
print('HOW BIG BRANDS HANDLE THIS:')
print('=' * 70)
print()
print('🌟 STELLARIUM:')
print('  - Uses magnitude cutoff based on zoom level')
print('  - Close up: shows faint stars (mag 6-7)')
print('  - Far out: hides faint stars, shows only bright ones')
print('  - Dynamic LOD (Level of Detail)')
print()
print('🚀 SPACE ENGINE:')
print('  - Scales star SIZES based on distance')
print('  - Far stars rendered smaller')
print('  - Culls stars outside frustum')
print('  - Uses magnitude-based filtering')
print()
print('🔭 CELESTIA:')
print('  - Fades out faint stars at distance')
print('  - Only renders stars in view frustum')
print('  - Limits total rendered stars to ~100k')
print()
print('=' * 70)
print('RECOMMENDATION FOR YOUR PROJECT:')
print('=' * 70)
print()
print('Option 1: MAGNITUDE FILTERING (Quick Fix)')
print('  - Only render stars brighter than magnitude 6.0')
print('  - Reduces clutter, keeps bright stars visible')
print('  - Easy to implement (1 line change)')
print()
print('Option 2: DISTANCE-BASED LOD (Better)')
print('  - Render all stars when close (<200pc)')
print('  - Filter to mag<6 when medium (200-500pc)')  
print('  - Filter to mag<4 when far (>500pc)')
print('  - More realistic depth perception')
print()
print('Option 3: STAR SIZE SCALING (Best for Realism)')
print('  - Already doing this!')
print('  - But maybe make faint stars even SMALLER')
print('  - So they contribute less to visual clutter')
print()
print('Current issue: You have 18,827 stars within 500pc')
print('Thats a LOT in one view! Consider filtering to ~5000-8000')

conn.close()
